//! FLAC is lossless by spec: decoding a FLAC file must reproduce the exact
//! PCM of its source. This proves `cochlea_decode::load` honors that for
//! both decode paths at once, by loading committed FLAC/WAV twins
//! (`tests/fixtures/`) and asserting the two `Audio` values are equal —
//! same sample rate, same channel count, every `f32` sample bit-for-bit
//! identical (`Audio` derives `PartialEq`, so this is exact equality, not
//! within-tolerance). See the `flac` module's docs (`src/flac.rs`) for why
//! that's actually guaranteed by construction, not a coincidence of two
//! libraries' rounding happening to agree.
//!
//! The twins are generated by [`regenerate_fixtures`] below, an `#[ignore]`d
//! test — never run in CI, only by a maintainer who wants to change or add
//! a fixture. It needs the system `flac` encoder on `PATH` (e.g. `brew
//! install flac` / `apt install flac`); the WAV side is synthesized
//! in-process with `hound` + `libm` so it's deterministic and needs no
//! external tool.

use std::path::{Path, PathBuf};

fn fixture_dir() -> PathBuf {
    PathBuf::from(format!("{}/tests/fixtures", env!("CARGO_MANIFEST_DIR")))
}

fn fixture(name: &str) -> PathBuf {
    fixture_dir().join(name)
}

fn assert_twins_match(stem: &str) {
    let wav = cochlea_decode::load(&fixture(&format!("{stem}.wav")))
        .unwrap_or_else(|err| panic!("loading {stem}.wav: {err}"));
    let flac = cochlea_decode::load(&fixture(&format!("{stem}.flac")))
        .unwrap_or_else(|err| panic!("loading {stem}.flac: {err}"));

    assert_eq!(wav.sample_rate, flac.sample_rate, "{stem}: sample_rate");
    assert_eq!(wav.channels, flac.channels, "{stem}: channels");
    assert_eq!(
        wav.samples.len(),
        flac.samples.len(),
        "{stem}: sample count"
    );
    assert_eq!(
        wav, flac,
        "{stem}: FLAC decode must be sample-exact vs its WAV twin"
    );
}

#[test]
fn mono_16bit_flac_matches_its_wav_twin() {
    assert_twins_match("tone_mono_16");
}

#[test]
fn stereo_16bit_flac_matches_its_wav_twin() {
    assert_twins_match("tone_stereo_16");
}

#[test]
fn stereo_24bit_flac_matches_its_wav_twin() {
    assert_twins_match("tone_stereo_24");
}

#[test]
fn unrecognized_extension_and_content_is_a_clear_error() {
    // An unknown extension falls back to content sniffing, so the error
    // only fires when the bytes are unrecognizable too.
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"));
    std::fs::create_dir_all(&dir).unwrap();
    let garbage = dir.join("not_audio.ogg");
    std::fs::write(&garbage, b"OggS this is not a format we decode").unwrap();

    let err = cochlea_decode::load(&garbage).expect_err(".ogg with non-WAV/FLAC bytes");
    assert!(matches!(
        err,
        cochlea_decode::DecodeError::UnsupportedExtension(ref ext) if ext == "ogg"
    ));
}

#[test]
fn extensionless_files_load_by_content_sniffing() {
    // The v1 CLI read WAVs purely by content (hound never saw the file
    // name); extension dispatch must not regress that — a valid WAV or
    // FLAC without any extension still loads via its magic bytes.
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"));
    std::fs::create_dir_all(&dir).unwrap();

    let bare_wav = dir.join("extensionless_wav");
    std::fs::copy(fixture("tone_mono_16.wav"), &bare_wav).unwrap();
    let from_wav = cochlea_decode::load(&bare_wav).expect("extensionless WAV must sniff as RIFF");
    let reference = cochlea_decode::load(&fixture("tone_mono_16.wav")).unwrap();
    assert_eq!(from_wav.samples, reference.samples);

    let bare_flac = dir.join("extensionless_flac");
    std::fs::copy(fixture("tone_mono_16.flac"), &bare_flac).unwrap();
    let from_flac =
        cochlea_decode::load(&bare_flac).expect("extensionless FLAC must sniff as fLaC");
    assert_eq!(from_flac.samples, reference.samples);
}

#[test]
fn uppercase_extension_still_dispatches() {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"));
    std::fs::create_dir_all(&dir).unwrap();
    let upper = dir.join("TONE_MONO_16.WAV");
    std::fs::copy(fixture("tone_mono_16.wav"), &upper).unwrap();

    let audio = cochlea_decode::load(&upper)
        .expect("uppercase .WAV extension must still dispatch to the WAV path");
    assert!(!audio.samples.is_empty());
}

#[test]
fn corrupt_flac_bytes_error_not_panic() {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"));
    std::fs::create_dir_all(&dir).unwrap();
    let garbage = dir.join("garbage.flac");
    std::fs::write(&garbage, b"this is not a flac stream, just garbage bytes").unwrap();

    let result = cochlea_decode::load(&garbage);
    assert!(
        result.is_err(),
        "garbage .flac bytes must return Err, not panic or silently succeed"
    );
}

// --- fixture regeneration (maintainer-only, never runs in CI) ---

/// A pure sine at half amplitude (headroom against quantization clipping
/// at the boundary sample), via `libm` — clippy's disallowed-methods ban on
/// std transcendentals applies to test code too, and there's no reason to
/// special-case fixture generation.
fn sine(freq_hz: f64, duration_s: f64, sample_rate: u32) -> Vec<f64> {
    let n = (duration_s * f64::from(sample_rate)).round() as usize;
    (0..n)
        .map(|i| {
            let t = i as f64 / f64::from(sample_rate);
            0.5 * libm::sin(2.0 * std::f64::consts::PI * freq_hz * t)
        })
        .collect()
}

/// Writes `channels` (each `[-0.5, 0.5]`-ranged, one `Vec` per channel, all
/// the same length) as an interleaved integer-PCM WAV at `bits_per_sample`.
fn write_wav(path: &Path, channels: &[Vec<f64>], sample_rate: u32, bits_per_sample: u16) {
    let full_scale = match bits_per_sample {
        16 => 32_768.0,
        24 => 8_388_608.0,
        other => panic!("fixture generator only supports 16/24-bit, got {other}"),
    };
    let spec = hound::WavSpec {
        channels: channels.len() as u16,
        sample_rate,
        bits_per_sample,
        sample_format: hound::SampleFormat::Int,
    };
    let mut writer = hound::WavWriter::create(path, spec).unwrap();
    let frames = channels[0].len();
    for frame in 0..frames {
        for channel in channels {
            let raw = (channel[frame] * full_scale).round() as i32;
            writer.write_sample(raw).unwrap();
        }
    }
    writer.finalize().unwrap();
}

/// Encodes `wav` to `flac` with the reference encoder, `--best` (doesn't
/// matter for correctness — FLAC is lossless at every compression level —
/// just keeps the committed file small).
fn encode_flac(wav: &Path, flac: &Path) {
    let status = std::process::Command::new("flac")
        .args(["--best", "--force", "-o"])
        .arg(flac)
        .arg(wav)
        .status()
        .expect(
            "the `flac` binary must be on PATH to regenerate fixtures \
             (e.g. `brew install flac` / `apt install flac`)",
        );
    assert!(status.success(), "flac encode failed for {}", wav.display());
}

#[test]
#[ignore = "regenerates committed fixtures; needs the system `flac` encoder \
            on PATH; never runs in CI — run explicitly with \
            `cargo test -p cochlea-decode --test sample_exact -- --ignored regenerate_fixtures`"]
fn regenerate_fixtures() {
    let dir = fixture_dir();
    std::fs::create_dir_all(&dir).unwrap();

    // 8 kHz, not a music-production rate, but decode correctness doesn't
    // depend on sample rate — chosen purely to keep the committed fixtures
    // tiny at the requested 0.5 s duration (48 kHz stereo/24-bit at 0.5 s
    // alone would be 144 KB of raw PCM; 8 kHz keeps the whole set under
    // 100 KB).
    const SAMPLE_RATE: u32 = 8_000;

    let mono = [sine(440.0, 0.5, SAMPLE_RATE)];
    write_wav(&dir.join("tone_mono_16.wav"), &mono, SAMPLE_RATE, 16);

    // Same stereo content (different L/R content, not just a mono signal
    // duplicated across channels) written at two bit depths, so
    // "tone_stereo_16" and "tone_stereo_24" are genuinely twins of each
    // other's content, not just independently-generated tones.
    let stereo = [sine(440.0, 0.5, SAMPLE_RATE), sine(554.0, 0.5, SAMPLE_RATE)];
    write_wav(&dir.join("tone_stereo_16.wav"), &stereo, SAMPLE_RATE, 16);
    write_wav(&dir.join("tone_stereo_24.wav"), &stereo, SAMPLE_RATE, 24);

    for stem in ["tone_mono_16", "tone_stereo_16", "tone_stereo_24"] {
        encode_flac(
            &dir.join(format!("{stem}.wav")),
            &dir.join(format!("{stem}.flac")),
        );
    }
}
